language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7

matrix:
  fast_finish: true

before_script:
  - dd if=/dev/urandom of=sample.txt bs=64M count=16

script:
  - df -h
  - ./create-archive.php
  - ./check-archive.php test-archive.zip